
import java.awt.Toolkit;
import static javax.swing.text.StyleConstants.setIcon;

/*
 *
 * @author Seyed Mahdi Arabi
 */
public class frmMain extends javax.swing.JFrame {

    public frmMain() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Calculator.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn0 = new javax.swing.JButton();
        btnFolat = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnMin = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnSum = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btnAC = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnBrace2 = new javax.swing.JButton();
        btnBrace1 = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnSin = new javax.swing.JButton();
        btnLn = new javax.swing.JButton();
        btnPI = new javax.swing.JButton();
        btnSqr = new javax.swing.JButton();
        btnPow = new javax.swing.JButton();
        btnRadian = new javax.swing.JRadioButton();
        btnDegree = new javax.swing.JRadioButton();
        Result = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(168, 169, 174));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(168, 169, 174));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn0.setBackground(new java.awt.Color(231, 232, 234));
        btn0.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 70, -1));

        btnFolat.setBackground(new java.awt.Color(231, 232, 234));
        btnFolat.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnFolat.setText(".");
        btnFolat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFolatActionPerformed(evt);
            }
        });
        jPanel1.add(btnFolat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 70, -1));

        btnEqual.setBackground(new java.awt.Color(231, 232, 234));
        btnEqual.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });
        jPanel1.add(btnEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 70, -1));

        btnDiv.setBackground(new java.awt.Color(231, 232, 234));
        btnDiv.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnDiv.setText("/");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });
        jPanel1.add(btnDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 70, -1));

        btnMin.setBackground(new java.awt.Color(231, 232, 234));
        btnMin.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnMin.setText("-");
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });
        jPanel1.add(btnMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 70, -1));

        btn3.setBackground(new java.awt.Color(231, 232, 234));
        btn3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 70, -1));

        btn2.setBackground(new java.awt.Color(231, 232, 234));
        btn2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 70, -1));

        btn1.setBackground(new java.awt.Color(231, 232, 234));
        btn1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, -1));

        btnSum.setBackground(new java.awt.Color(231, 232, 234));
        btnSum.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnSum.setText("+");
        btnSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumActionPerformed(evt);
            }
        });
        jPanel1.add(btnSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 70, -1));

        btn6.setBackground(new java.awt.Color(231, 232, 234));
        btn6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 70, -1));

        btn5.setBackground(new java.awt.Color(231, 232, 234));
        btn5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 70, -1));

        btn4.setBackground(new java.awt.Color(231, 232, 234));
        btn4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, -1));

        btnMulti.setBackground(new java.awt.Color(231, 232, 234));
        btnMulti.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnMulti.setText("*");
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });
        jPanel1.add(btnMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 70, -1));

        btn9.setBackground(new java.awt.Color(231, 232, 234));
        btn9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 70, -1));

        btn8.setBackground(new java.awt.Color(231, 232, 234));
        btn8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 70, -1));

        btn7.setBackground(new java.awt.Color(231, 232, 234));
        btn7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, -1));

        btnAC.setBackground(new java.awt.Color(231, 232, 234));
        btnAC.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnAC.setText("AC");
        btnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACActionPerformed(evt);
            }
        });
        jPanel1.add(btnAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 70, -1));

        btnDel.setBackground(new java.awt.Color(231, 232, 234));
        btnDel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnDel.setText("Del");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jPanel1.add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 70, -1));

        btnBrace2.setBackground(new java.awt.Color(231, 232, 234));
        btnBrace2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnBrace2.setText(")");
        btnBrace2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrace2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBrace2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 70, -1));

        btnBrace1.setBackground(new java.awt.Color(231, 232, 234));
        btnBrace1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnBrace1.setText("(");
        btnBrace1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrace1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBrace1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, -1));

        btnLog.setBackground(new java.awt.Color(231, 232, 234));
        btnLog.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnLog.setText("Log");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });
        jPanel1.add(btnLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 70, -1));

        btnTan.setBackground(new java.awt.Color(231, 232, 234));
        btnTan.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnTan.setText("Tan");
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanActionPerformed(evt);
            }
        });
        jPanel1.add(btnTan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 70, -1));

        btnCos.setBackground(new java.awt.Color(231, 232, 234));
        btnCos.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnCos.setText("Cos");
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });
        jPanel1.add(btnCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 70, -1));

        btnSin.setBackground(new java.awt.Color(231, 232, 234));
        btnSin.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnSin.setText("Sin");
        btnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinActionPerformed(evt);
            }
        });
        jPanel1.add(btnSin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, -1));

        btnLn.setBackground(new java.awt.Color(231, 232, 234));
        btnLn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnLn.setText("Ln");
        btnLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLnActionPerformed(evt);
            }
        });
        jPanel1.add(btnLn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 70, -1));

        btnPI.setBackground(new java.awt.Color(231, 232, 234));
        btnPI.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnPI.setText("PI");
        btnPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPIActionPerformed(evt);
            }
        });
        jPanel1.add(btnPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 70, -1));

        btnSqr.setBackground(new java.awt.Color(231, 232, 234));
        btnSqr.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnSqr.setText("√");
        btnSqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSqrActionPerformed(evt);
            }
        });
        jPanel1.add(btnSqr, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 70, -1));

        btnPow.setBackground(new java.awt.Color(231, 232, 234));
        btnPow.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnPow.setText("^");
        btnPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowActionPerformed(evt);
            }
        });
        jPanel1.add(btnPow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, -1));

        buttonGroup2.add(btnRadian);
        btnRadian.setText("Radian");
        btnRadian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadianActionPerformed(evt);
            }
        });
        jPanel1.add(btnRadian, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, -1));

        buttonGroup2.add(btnDegree);
        btnDegree.setText("Degree");
        jPanel1.add(btnDegree, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 300, 330));

        Result.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        Result.setForeground(new java.awt.Color(255, 255, 255));
        Result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, 40));
        Result.getAccessibleContext().setAccessibleParent(jLabel1);

        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, -1));

        jPanel2.setLayout(null);
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        Result.setText(Result.getText()+"0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        Result.setText(Result.getText()+"4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        Result.setText(Result.getText()+"/");
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnFolatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFolatActionPerformed
        Result.setText(Result.getText()+".");
    }//GEN-LAST:event_btnFolatActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        Calculate c = new Calculate ();
        Result.setText (c.Evaluation(Result.getText(),btnDegree.isSelected()));

    }//GEN-LAST:event_btnEqualActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        Result.setText(Result.getText()+"1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        Result.setText(Result.getText()+"2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        Result.setText(Result.getText()+"3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
        Result.setText(Result.getText()+"-");
    }//GEN-LAST:event_btnMinActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        Result.setText(Result.getText()+"5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        Result.setText(Result.getText()+"6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btnSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumActionPerformed
        Result.setText(Result.getText()+"+");
    }//GEN-LAST:event_btnSumActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        Result.setText(Result.getText()+"7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        Result.setText(Result.getText()+"8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        Result.setText(Result.getText()+"9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
        Result.setText(Result.getText()+"*");
    }//GEN-LAST:event_btnMultiActionPerformed

    private void btnBrace1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrace1ActionPerformed
        Result.setText(Result.getText()+"(");
    }//GEN-LAST:event_btnBrace1ActionPerformed

    private void btnBrace2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrace2ActionPerformed
        Result.setText(Result.getText()+")");
    }//GEN-LAST:event_btnBrace2ActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        Result.setText(Result.getText().substring(0,Result.getText().length()-1));
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACActionPerformed
        Result.setText("");
    }//GEN-LAST:event_btnACActionPerformed

    private void btnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinActionPerformed
        Result.setText(Result.getText()+"Sin");
    }//GEN-LAST:event_btnSinActionPerformed

    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        Result.setText(Result.getText()+"Cos");
    }//GEN-LAST:event_btnCosActionPerformed

    private void btnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanActionPerformed
        Result.setText(Result.getText()+"Tan");
    }//GEN-LAST:event_btnTanActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        Result.setText(Result.getText()+"Log");
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowActionPerformed
        Result.setText(Result.getText()+"^");
    }//GEN-LAST:event_btnPowActionPerformed

    private void btnSqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSqrActionPerformed
       Result.setText(Result.getText()+"Sqr");
    }//GEN-LAST:event_btnSqrActionPerformed

    private void btnPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPIActionPerformed
       Result.setText(Result.getText()+Math.PI);

    }//GEN-LAST:event_btnPIActionPerformed

    private void btnLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLnActionPerformed
        Result.setText(Result.getText()+"Ln");
    }//GEN-LAST:event_btnLnActionPerformed

    private void btnRadianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRadianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Result;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAC;
    private javax.swing.JButton btnBrace1;
    private javax.swing.JButton btnBrace2;
    private javax.swing.JButton btnCos;
    private javax.swing.JRadioButton btnDegree;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnFolat;
    private javax.swing.JButton btnLn;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnMin;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnPI;
    private javax.swing.JButton btnPow;
    private javax.swing.JRadioButton btnRadian;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnSqr;
    private javax.swing.JButton btnSum;
    private javax.swing.JButton btnTan;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
